endpoint:
  stack_name: k8s-gaudi-only-granite-trim
  model: ibm-granite/granite-4.1-8b
  namespace: llm-d-granite-kv
  base_url: http://decode-clusterip.llm-d-granite-kv.svc.cluster.local:8000
  hf_token_secret: llm-d-hf-token
control:
  work_dir: $HOME/llm-d-bench-work-gaudi-only-k8s-trim
  kubectl: kubectl
harness:
  name: inference-perf
  namespace: llm-d-granite-kv
  parallelism: 1
  wait_timeout: 6000
  image: ghcr.io/llm-d/llm-d-benchmark:v0.5.2
  results_pvc: ''
env:
- name: RAYON_NUM_THREADS
  value: '4'
workload:
  shared_prefix:
    load:
      type: poisson
      stages:
      - rate: 10
        duration: 50
      - rate: 3
        duration: 30
      - rate: 8
        duration: 30
      - rate: 15
        duration: 30
      - rate: 25
        duration: 30
    api:
      type: completion
      streaming: true
    server:
      type: vllm
      model_name: ibm-granite/granite-4.1-8b
      base_url: http://decode-clusterip.llm-d-granite-kv.svc.cluster.local:8000
      ignore_eos: true
    tokenizer:
      pretrained_model_name_or_path: ibm-granite/granite-4.1-8b
    data:
      type: shared_prefix
      shared_prefix:
        num_groups: 150
        num_prompts_per_group: 5
        system_prompt_len: 6000
        question_len: 1200
        output_len: 1000
        enable_multi_turn_chat: false
    report:
      request_lifecycle:
        summary: true
        per_stage: true
        per_request: true
    storage:
      local_storage:
        path: /workspace
